
USE K_COVID19;

-- 자식 부모 (부모는 null값 있으면 안 됨) --

ALTER TABLE REGION ADD FOREIGN KEY (region_code) REFERENCES WEATHER (region_code) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE PATIENTINFO ADD FOREIGN KEY (province) REFERENCES REGION (province) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE WEATHER ADD FOREIGN KEY (wdate) REFERENCES PATIENTINFO (confirmed_date) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE PATIENTINFO ADD FOREIGN KEY (infection_case) REFERENCES CASEINFO (infection_case) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE PATIENTINFO ADD FOREIGN KEY (province) REFERENCES WEATHER (province) ON DELETE SET NULL ON UPDATE CASCADE;
